apiVersion: v1
kind: Service
metadata:
  name: pghost # acts as DNS!
  namespace: xoom
spec:
  selector:
    tier: database
    appName: pod-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-database
  namespace: xoom
  labels:
    tier: database
    type: deployment-postgresql
spec:
  selector:
    matchLabels:
      tier: database
      appName: pod-postgresql
  template:
    metadata:
      labels:
        system: xoom-distributed-cqrs
        tier: database
        appName: pod-postgresql
    spec:
      containers:
        - name: postgresql-database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: xoomdb
            - name: POSTGRES_USER
              value: xoom_test
            - name: POSTGRES_PASSWORD
              value: xoom123
      volumes:
      - name: postgresql-volume
